Basic Slicing and indexing : Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
a slice object that is of the form start : stop : step
an integer
or a tuple of slice objects and integers
All arrays generated by basic slicing are always view of the original array.

filter_none
edit
play_arrow

brightness_4
# Python program for basic slicing. 
import numpy as np 
  
# Arrange elements from 0 to 19 
a = np.arange(20) 
print("\n Array is:\n ",a) 
  
# a[start:stop:step] 
print("\n a[-8:17:1]  = ",a[-8:17:1])  
  
# The : operator means all elements till the end. 
print("\n a[10:]  = ",a[10:]) 